### PR TITLE
feat: update to api v42

### PR DESCRIPTION
**Pull request by shiftinv**
## Summary

is moar faster

## Checklist

- [x] If code changes were made, then they have been tested
    - [ ] I have updated the documentation to reflect the changes
    - [ ] I have formatted the code properly by running `task lint`
    - [ ] I have type-checked the code by running `task pyright`
- [ ] This PR fixes an issue
- [ ] This PR adds something new (e.g. new method or parameters)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by onerandomusername — CHANGES_REQUESTED** [review]
this errors with invalid api version why is that?

**Comment by shiftinv** [comment]
> this errors with invalid api version why is that?

Not sure :thonk:
the docs claim it's supported
image

and when I tested it, my bot's ping changed from 110ms to 750ns on average (if there's a full moon)

**Comment by onerandomusername** [comment]
@shiftinv why was this closed? Its a perfectly bad change to an otherwise good commit history

**Comment by onerandomusername** [comment]
https://github.com/onerandomusername/snakebot/pull/27

https://github.com/onerandomusername/goodbot/pull/27

**Pull request closed without merging**
